#!/bin/bash
# Google Chat Setup Script for UltraX Gateway
# Part of Ultrapilot unified setup

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║        📱 GOOGLE CHAT SETUP FOR ULTRAX GATEWAY                ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

# Check if already configured
if [ -f .ultra/google-chat-config.sh ]; then
    echo "⚠️  Google Chat already configured."
    echo "Current config:"
    source .ultra/google-chat-config.sh
    echo "   Webhook URL: ${GOOGLE_CHAT_WEBHOOK_URL:0:50}..."
    echo ""
    read -p "Reconfigure? (y/N): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "✅ Keeping existing configuration."
        exit 0
    fi
fi

echo "📋 STEP 1: Create Google Chat Webhook"
echo "────────────────────────────────────────"
echo ""
echo "1. Open Google Chat"
echo "2. Go to the Space/Room where you want UltraX to send messages"
echo "3. Click the dropdown arrow next to the space name"
echo "4. Select 'Configure webhooks'"
echo "5. Click 'Add webhook'"
echo "6. Name it: UltraX Bot"
echo "7. Avatar URL (optional): https://github.com/hscheema1979.png"
echo "8. Click 'SAVE'"
echo "9. Copy the webhook URL"
echo ""
read -p "Press Enter when you have your webhook URL..."

echo ""
echo "📋 STEP 2: Enter Webhook URL"
echo "────────────────────────────────────────"
read -p "Paste your Google Chat webhook URL: " WEBHOOK_URL

if [[ -z "$WEBHOOK_URL" ]]; then
    echo "❌ Webhook URL cannot be empty."
    exit 1
fi

# Validate URL format
if [[ ! "$WEBHOOK_URL" =~ ^https://chat\.googleapis\.com/v1/spaces/ ]]; then
    echo "⚠️  Warning: URL doesn't look like a Google Chat webhook URL."
    read -p "Continue anyway? (y/N): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

echo ""
echo "📋 STEP 3: Test Webhook Connection"
echo "────────────────────────────────────────"
read -p "Send test message to Google Chat? (Y/n): " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]] || [[ -z $REPLY ]]; then
    echo "📤 Sending test message..."
    RESPONSE=$(curl -s -X POST "$WEBHOOK_URL" \
        -H "Content-Type: application/json" \
        -d '{"text": "🦎 UltraX Bot connected! This is a test message from your Ultrapilot setup."}')

    if [[ -z "$RESPONSE" ]]; then
        echo "✅ Test message sent successfully!"
    else
        echo "⚠️  Response: $RESPONSE"
    fi
fi

echo ""
echo "📋 STEP 4: Save Configuration"
echo "────────────────────────────────────────"

# Create .ultra directory if it doesn't exist
mkdir -p .ultra

# Save configuration
cat > .ultra/google-chat-config.sh << EOF
# Google Chat Configuration for UltraX Gateway
# Generated by setup-google-chat.sh

export GOOGLE_CHAT_WEBHOOK_URL="$WEBHOOK_URL"
EOF

chmod 600 .ultra/google-chat-config.sh

echo "✅ Configuration saved to .ultra/google-chat-config.sh"

echo ""
echo "📋 STEP 5: Update systemd Service"
echo "────────────────────────────────────────"
read -p "Configure systemd service to use webhook? (Y/n): " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]] || [[ -z $REPLY ]]; then
    if [ -f /etc/systemd/system/ultrax-server.service ]; then
        echo "📝 Creating systemd override..."

        # Create override directory
        sudo mkdir -p /etc/systemd/system/ultrax-server.service.d/

        # Create override file
        sudo tee /etc/systemd/system/ultrax-server.service.d/override.conf > /dev/null << EOF
[Service]
Environment="GOOGLE_CHAT_WEBHOOK_URL=$WEBHOOK_URL"
EOF

        echo "♻️  Reloading systemd..."
        sudo systemctl daemon-reload

        echo "🔄 Restarting ultrax-server..."
        sudo systemctl restart ultrax-server

        sleep 2

        if sudo systemctl is-active --quiet ultrax-server; then
            echo "✅ UltraX Gateway restarted successfully"
        else
            echo "⚠️  Warning: UltraX gateway may not be running"
            sudo systemctl status ultrax-server --no-pager
        fi
    else
        echo "⚠️  systemd service not found. You'll need to configure this manually."
        echo ""
        echo "Add this line to your service configuration:"
        echo "Environment=\"GOOGLE_CHAT_WEBHOOK_URL=$WEBHOOK_URL\""
    fi
fi

echo ""
echo "📋 STEP 6: Test Integration"
echo "────────────────────────────────────────"
echo "Testing webhook endpoint..."
sleep 2

HEALTH_CHECK=$(curl -s http://localhost:3001/health)
if [ -n "$HEALTH_CHECK" ]; then
    echo "✅ UltraX Gateway is running"

    WEBHOOK_TEST=$(curl -s -X POST http://localhost:3001/webhook/google-chat \
        -H "Content-Type: application/json" \
        -d '{"message": "Setup test"}')

    if [[ "$WEBHOOK_TEST" == *"OK"* ]] || [[ -z "$WEBHOOK_TEST" ]]; then
        echo "✅ Google Chat webhook endpoint working!"
    else
        echo "⚠️  Webhook response: $WEBHOOK_TEST"
        echo "Note: If you see 'Google Chat bot not configured', restart the gateway."
    fi
else
    echo "⚠️  UltraX Gateway not responding on port 3001"
fi

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                    ✅ SETUP COMPLETE                          ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "📚 Next Steps:"
echo ""
echo "1. Check your Google Chat space for the test message"
echo ""
echo "2. Send commands via Google Chat:"
echo "   • /ultrapilot <task> - Run autonomous development"
echo "   • /status - Check system status"
echo "   • /help - Show available commands"
echo ""
echo "3. Monitor logs:"
echo "   sudo journalctl -u ultrax-server -f"
echo ""
echo "4. Configuration saved in:"
echo "   .ultra/google-chat-config.sh"
echo ""
echo "5. To reconfigure, run:"
echo "   ./setup-google-chat.sh"
echo ""
